jobs:
 - name: aarch64_u16all-testing
   type: runSh
   steps:
     - TASK:
         runtime:
           options:
             imageName: "drydock/aarch64_u16all"
             imageTag: master
         script:
       
           - elasticsearch --version
           - memcached -V
           - mongod --version
           - /var/lib/neo4j/bin/neo4j version
           - psql --version
           - dpkg -s rabbitmq-server | grep Version
           - java -jar /usr/local/selenium/selenium-server-standalone-3.11.0.jar --version
           - sqlite3 --version
           - service couchdb start
           - sleep 5
           - curl http://127.0.0.1:5984/
           
           

